package com.example.healthconnect.utilty.impl.ui.editor

import androidx.health.connect.client.records.*
import com.example.healthconnect.utilty.api.domain.record.*
import com.example.healthconnect.utilty.impl.ui.editor.record.*
import kotlin.reflect.KClass

class EditorFactory {

    @Suppress("UNCHECKED_CAST")
    fun createByRecord(
        recordKClass: KClass<out Record>,
    ): Editor<Record, Model> = when (recordKClass) {
        BasalBodyTemperatureRecord::class -> BasalBodyTemperatureEditor()
        BodyTemperatureRecord::class -> BodyTemperatureEditor()
        BasalMetabolicRateRecord::class -> BasalMetabolicRateEditor()
        BloodGlucoseRecord::class -> BloodGlucoseEditor()
        BloodPressureRecord::class -> BloodPressureEditor()
        BodyFatRecord::class -> BodyFatEditor()
        BodyWaterMassRecord::class -> BodyWaterMassEditor()
        BoneMassRecord::class -> BoneMassEditor()
        CervicalMucusRecord::class -> CervicalMucusEditor()
        HeartRateVariabilityRmssdRecord::class -> HeartRateVariabilityRmssdEditor()
        HeightRecord::class -> HeightEditor()
        IntermenstrualBleedingRecord::class -> IntermenstrualBleedingEditor()
        LeanBodyMassRecord::class -> LeanBodyMassEditor()
        WeightRecord::class -> WeightEditor()
        OxygenSaturationRecord::class -> OxygenSaturationEditor()
        RespiratoryRateRecord::class -> RespiratoryRateEditor()
        MenstruationFlowRecord::class -> MenstruationFlowEditor()
        OvulationTestRecord::class -> OvulationTestEditor()
        SexualActivityRecord::class -> SexualActivityEditor()
        Vo2MaxRecord::class -> Vo2MaxEditor()
        RestingHeartRateRecord::class -> RestingHeartRateEditor()
        ActiveCaloriesBurnedRecord::class -> ActiveCaloriesBurnedEditor()
        DistanceRecord::class -> DistanceEditor()
        ElevationGainedRecord::class -> ElevationGainedEditor()
        HydrationRecord::class -> HydrationEditor()
        ActivityIntensityRecord::class -> ActivityIntensityEditor()
        FloorsClimbedRecord::class -> FloorsClimbedEditor()
        MenstruationPeriodRecord::class -> MenstruationPeriodEditor()
        MindfulnessSessionRecord::class -> MindfulnessSessionEditor()
        ExerciseSessionRecord::class -> ExerciseSessionEditor()
        PlannedExerciseSessionRecord::class -> PlannedExerciseSessionEditor()
        NutritionRecord::class -> NutritionEditor()
        SkinTemperatureRecord::class -> SkinTemperatureEditor()
        SleepSessionRecord::class -> SleepSessionEditor()
        StepsRecord::class -> StepsEditor()
        TotalCaloriesBurnedRecord::class -> TotalCaloriesBurnedEditor()
        WheelchairPushesRecord::class -> WheelchairPushesEditor()
        HeartRateRecord::class -> HeartRateEditor()
        CyclingPedalingCadenceRecord::class -> CyclingPedalingCadenceEditor()
        PowerRecord::class -> PowerEditor()
        SpeedRecord::class -> SpeedEditor()
        StepsCadenceRecord::class -> StepsCadenceEditor()
        else -> throw NotImplementedError()
    } as Editor<Record, Model>

    @Suppress("UNCHECKED_CAST")
    fun createByModel(
        modelKClass: KClass<out Model>,
    ): Editor<Record, Model> = when (modelKClass) {
        BasalBodyTemperature::class -> BasalBodyTemperatureEditor()
        BodyTemperature::class -> BodyTemperatureEditor()
        BasalMetabolicRate::class -> BasalMetabolicRateEditor()
        BloodGlucoseLevel::class -> BloodGlucoseEditor()
        BloodPressure::class -> BloodPressureEditor()
        BodyFat::class -> BodyFatEditor()
        BodyWaterMass::class -> BodyWaterMassEditor()
        BoneMass::class -> BoneMassEditor()
        CervicalMucus::class -> CervicalMucusEditor()
        HeartRateVariabilityRmssd::class -> HeartRateVariabilityRmssdEditor()
        Height::class -> HeightEditor()
        IntermenstrualBleeding::class -> IntermenstrualBleedingEditor()
        LeanBodyMass::class -> LeanBodyMassEditor()
        Weight::class -> WeightEditor()
        OxygenSaturation::class -> OxygenSaturationEditor()
        RespiratoryRate::class -> RespiratoryRateEditor()
        MenstruationFlow::class -> MenstruationFlowEditor()
        OvulationTest::class -> OvulationTestEditor()
        SexualActivity::class -> SexualActivityEditor()
        Vo2Max::class -> Vo2MaxEditor()
        RestingHeartRate::class -> RestingHeartRateEditor()
        ActiveCaloriesBurned::class -> ActiveCaloriesBurnedEditor()
        Distance::class -> DistanceEditor()
        ElevationGained::class -> ElevationGainedEditor()
        Hydration::class -> HydrationEditor()
        ActivityIntensity::class -> ActivityIntensityEditor()
        FloorsClimbed::class -> FloorsClimbedEditor()
        MenstruationPeriod::class -> MenstruationPeriodEditor()
        MindfulnessSession::class -> MindfulnessSessionEditor()
        ExerciseSession::class -> ExerciseSessionEditor()
        PlannedExerciseSession::class -> PlannedExerciseSessionEditor()
        Nutrition::class -> NutritionEditor()
        SkinTemperature::class -> SkinTemperatureEditor()
        SleepSession::class -> SleepSessionEditor()
        Steps::class -> StepsEditor()
        TotalCaloriesBurned::class -> TotalCaloriesBurnedEditor()
        WheelchairPushes::class -> WheelchairPushesEditor()
        HeartRate::class -> HeartRateEditor()
        CyclingPedalingCadence::class -> CyclingPedalingCadenceEditor()
        Power::class -> PowerEditor()
        Speed::class -> SpeedEditor()
        StepsCadence::class -> StepsCadenceEditor()
        else -> throw NotImplementedError()
    } as Editor<Record, Model>
}
